import org.jetbrains.kotlin.gradle.dsl.JvmDefaultMode
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile
import tapmoc.Severity

buildscript {
	dependencies {
		classpath libs.kotlin.gradlePlugin
		classpath libs.dokkaPlugin
		classpath libs.gradleMavenPublishPlugin
		classpath libs.spotlessPlugin
		classpath libs.android.gradlePlugin
		classpath libs.compatPlugin
		classpath libs.buildConfigPlugin
	}
	repositories {
		mavenCentral()
		google()
	}
}

subprojects {
	repositories {
		mavenCentral()
		google()
		maven {
			url 'https://repo.gradle.org/gradle/libs-releases'
			metadataSources {
				mavenPom()
				ignoreGradleMetadataRedirection()
			}
		}
	}

	pluginManager.withPlugin('org.jetbrains.kotlin.jvm') {
		apply plugin: 'com.gradleup.tapmoc'
		tapmoc {
			java(17)
			kotlin('2.2.0')
			checkApiDependencies(Severity.ERROR)
			checkRuntimeDependencies(Severity.ERROR)
		}
	}

	tasks.withType(KotlinJvmCompile).configureEach { task ->
		task.compilerOptions {
			jvmDefault = JvmDefaultMode.NO_COMPATIBILITY
		}
	}

	tasks.withType(Test).configureEach {
		testLogging {
			if (System.getenv('CI') == 'true') {
				events = ['failed', 'skipped', 'passed']
			}
			exceptionFormat 'full'
		}
	}

	pluginManager.withPlugin('com.vanniktech.maven.publish') {
		publishing {
			repositories {
				maven {
					name = 'testing'
					url = "${rootProject.projectDir}/build/localMaven"
				}
			}
		}
	}

	apply plugin: 'com.diffplug.spotless'
	spotless {
		kotlin {
			target('**/*.kt')
			targetExclude('**/src/test/test-build-logic/build/**', '**/generated-sources/**')
			ktlint(libs.ktlint.get().version).editorConfigOverride([
				'ktlint_standard_filename'                : 'disabled',
				// Making something an expression body should be a choice around readability.
				'ktlint_standard_function-expression-body': 'disabled',
			])
		}
	}
}
