buildscript {
	dependencies {
		classpath "com.jakewharton.gradle:test-distribution-gradle-plugin:$testDistributionVersion"
	}

	repositories {
		maven {
			url "file://${rootDir.absolutePath}/../../../../../build/localMaven"
		}
		mavenCentral()
	}
}

apply plugin: 'java'
apply plugin: 'com.jakewharton.test-distribution'

dependencies {
	testImplementation libs.junit
}
